pawame/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views
from django.contrib.auth import views as auth_views




urlpatterns = [
    path('admin/', admin.site.urls),
    path(
      'admin/password_reset/',
      auth_views.PasswordResetView.as_view(),
     name='admin_password_reset',
    ),
    path(
         'admin/password_reset/done/',
      auth_views.PasswordResetDoneView.as_view(),{"success_url":""},
       name='password_reset_done',
     ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm',
    ),
     path(
         'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete',
    ),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('intranet.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


    # path('accounts/',include('authtools.urls')),

]

intranet/models.py
from django.db import models
from django.contrib.auth.models import(
    BaseUserManager, AbstractBaseUser, PermissionsMixin)
import online_users.models
from datetime import timedelta
from django.shortcuts import get_object_or_404
from django.core.cache import cache
import datetime
from pawame import settings
from tinymce.models import HTMLField
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.models.signals import Signal
from pawame.settings import AUTH_USER_MODEL


class MyUserManager(BaseUserManager):
    def create_user(self, email, user_type, department, username, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
            email=self.normalize_email(email),
            username=username,
            user_type=user_type,
            department=department,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, user_type, username, password=None):

        user = self.create_user(
            email,
            user_type=user_type,
            department=None,
            username=username,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):

    USER_TYPES_CHOICES = (
        (1, 'SuperAdmin'),
        (2, 'Admin'),
        (3, 'Employee'),
    )
    DEPARTMENTS = (
        (1, 'Human Resource'),
        (2, 'Inventory'),
        (3, 'Finance'),
        (4, 'Marketing'),
        (5, 'Information Technology'),
    )
    email = models.EmailField(max_length=100, unique=True)
    username = models.CharField(max_length=200)
    employee_id = models.IntegerField(blank=True, null=True)
    user_type = models.PositiveSmallIntegerField(choices=USER_TYPES_CHOICES)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    department = models.PositiveSmallIntegerField(choices=DEPARTMENTS, null=True)
    image = models.ImageField(upload_to='photos/', null=True)
    is_online = models.BooleanField(default=False)


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'user_type']

    objects = MyUserManager()

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @classmethod
    def search_employees(cls, employee):
        employee = cls.objects.filter(username__icontains=employee)
        return employee

    @property
    def is_staff(self):
        return self.is_admin


class Profile(models.Model):
    image = models.ImageField(upload_to='photos/', blank=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def save_profile(self):
        self.save()

    def delete_profile(self):
        self.delete()

    @classmethod
    def update_profile(cls, id, first_name):
        cls.objects.filter(pk=id).update(first_name=first_name)
        new_name_object = cls.objects.get(first_name=first_name)
        new_name = new_name_object.first_name
        return new_name

    def __str__(self):
        return self.first_name

    def last_seen(self):
        return cache.get('seen_%s' % self.user.username)

    def online(self):
        if self.last_seen():
            now = datetime.datetime.now()
            if now > self.last_seen() + datetime.timedelta(
                    seconds=settings.USER_ONLINE_TIMEOUT):
                return False
            else:
                return True
        else:
            return False
        
    @receiver(post_save, sender=AUTH_USER_MODEL)
    def create_profile(sender, instance,created,**kwargs):
        if created:
            Profile.objects.create(user=instance)
    
    @receiver(post_save, sender=AUTH_USER_MODEL)
    def save_profile(sender, instance, **kwargs):
        instance.profile.save()


class Updates(models.Model):

    UPDATE_TYPES = (
        (1, 'General'),
        (2, 'Human Resource'),
        (3, 'Information_technology'),
        (4, 'Inventory'),
        (5, 'Marketing'),
        (6, 'Finance'),
    )
    title = models.CharField(max_length=70)
    update = HTMLField()
    time_stamp = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    department = models.PositiveSmallIntegerField(
        choices=UPDATE_TYPES, null=True)
    status = models.BooleanField(default=False)

    @classmethod
    def get_update(cls, id):
        update = get_object_or_404(cls, pk=id)

    @classmethod
    def approved(cls, id):
        update = get_object_or_404(cls, pk=id)
        update.status = True
        update.save()
        return update.status

    @classmethod
    def dissaprove(cls, id):
        update = get_object_or_404(cls, pk=id)
        update.delete()
        return None

    def __str__(self):
        return self.title


class Comments(models.Model):
    comment = models.CharField(max_length=1000)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    update = models.ForeignKey(Updates, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(auto_now_add=True)

    @classmethod
    def get_comments(cls, id):
        comments = cls.objects.filter(update__id=id)
        return comments

    def save_comment(self):
        self.save()

    def __str__(self):
        return self.comment

templates/commenting.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}

{% block content %}


<div class="container">
{{ request.update }}

    {% if update.department == 1 %}
        <h3 class="text-center font-weight-bolder pt-3 pb-3" style="color: #0B920D;"> General: {{update.title}} </h3>
        {% elif update.department == 2 %}
        <h3 class="text-center font-weight-bolder pt-3 pb-3" style="color: #0B920D;"> Human Resource Department: {{update.title}} </h3>
        {% elif update.department == 3 %}
        <h3 class="text-center font-weight-bolder pt-3 pb-3" style="color: #0B920D;"> Information Technology Department: {{update.title}} </h3>
        {% elif update.department == 4 %}
        <h3 class="text-center font-weight-bolder pt-3 pb-3" style="color: #0B920D;"> Inventory Department: {{update.title}} </h3>
        {% elif update.department == 5 %}
        <h3 class="text-center font-weight-bolder pt-3 pb-3" style="color: #0B920D;"> Marketing Department: {{update.title}}  </h3>
        {% elif update.department == 6 %}
        <h3 class="text-center font-weight-bolder pt-3 pb-3" style="color: #0B920D;"> Finance Department: {{update.title}} </h3>
    {% endif %}
  <hr>


  <div id="{{update.id}}" class="row">

    <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
      {% if update.user.profile.image %}
        <img class="d-flex rounded-circle avatar z-depth-1-quater mr-3"
          src="{{update.user.profile.image.url}}" height="100px" width="100px" alt="Avatar">
      {% else %}
          <img class="d-flex rounded-circle avatar z-depth-1-half mr-3"
          src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmgQLi9YIA2uiwnuZ_LU_K-nOVMvilA2A5M2dNNescwKKBm6EI&s" height="100px" width="100px" alt="Avatar">
      {% endif %}
    </div>


    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
      <h5 class="mt-0 font-weight-bold dark-text post-content">{{ update.title }}</h5>

      <p class="post-content" style="max-width: 100%;">  
      {% autoescape on %}
        {{ update.update|safe }}
      {% endautoescape %}
      </p>

      <h6 class="text-muted pt-2 post-date">
        <i>Posted by {{ update.user }}: {{ update.time_stamp|timesince }} ago </i>
      </h6>

          <div class="accordion" id="accordionExample275">
                  <button class="btn btn-sm btn-link" type="button" data-toggle="collapse" href="#collapse{{ update.id}}"
                    aria-expanded="false" aria-controls="collapseOne2">
                    View {{ update.comments_set.all|length }} comment{{update.comments_set.all|pluralize}}
                  </button>
              <div id="collapse{{ update.id }}" class="collapse">
                  
                  {% for comment in update.comments_set.all %}

                  <p> 

                  {% if comment.user.profile.image %}

                  
                  <img class="rounded-circle avatar z-depth-1-half mr-1" src="{{comment.user.profile.image.url}}" style="width:30px; height:30px;"> 

                  {% else %}

                   <img class="rounded-circle avatar z-depth-1-half mr-1" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmgQLi9YIA2uiwnuZ_LU_K-nOVMvilA2A5M2dNNescwKKBm6EI&s" style="width:30px; height:30px;"> 

                  {% endif %}
                  
                  <strong> {{ comment.user }}</strong> said: {{ comment.comment }} <br>
                  <span class="text-muted"> {{comment.date_posted|timesince}} ago </span>
                  </p>

                  {% endfor %}

              </div>
            
          </div>
      
      <div class="row mt-3 shadow-textarea">

        <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1">
            {% if request.user.profile.image %}

            <img class="d-flex rounded-circle avatar z-depth-1-half"
              src="{{request.user.profile.image.url}}" height="40px" width="40px"
              alt="Generic placeholder image">
            
            {% else %}
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmgQLi9YIA2uiwnuZ_LU_K-nOVMvilA2A5M2dNNescwKKBm6EI&s" height="40px" width="40px" alt="avatar mx-auto white" class="rounded-circle img-fluid avatar z-depth-1-half">
            {% endif %}
        </div>

        <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10 pl-0">
          <div class="form-group basic-textarea rounded-corners commentForm">

            <form action="{% url 'comments' update_id=update.id %}" method="post" onsubmit="myFunction()" id="commentForm">

            <input type="hidden" name="next" value="{{ request.get_full_path }}">

            {% csrf_token %}
              
            {% bootstrap_form commentForm layout='inline '%}
            
              <button type="submit" class="btn btn-success btn-sm px-2 py-1"><i class="far fa-thumbs-up mr-2" aria-hidden="true"></i>Post Comment</button>

            </form>

          <!-- snackbar -->
            <div id="snackbar" class="btn btn-sm btn-green ml-auto">Your comment has been published</div>
          <!-- end of snackbar -->
          </div>
        </div>
      </div>
    </div>
  </div>


    <div class="row onlineUsers">
          <button id="popover" class="btn btn-sm btn-green ml-auto" title="Employee Online Status" data-toggle="popover"  data-placement="top" data-trigger="focus"> Who's online? </button>

          <div id="popover-content" style="display:none;">
          {% for user in users %}
            {% if user.profile.is_online %}
              <p>
                  {% if user.profile.image %}                 
                  <img class="rounded-circle avatar z-depth-1-half mr-1" src="{{user.profile.image.url}}" style="width:30px; height:30px;"> 
                  {% else %}
                   <img class="rounded-circle avatar z-depth-1-half mr-1" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmgQLi9YIA2uiwnuZ_LU_K-nOVMvilA2A5M2dNNescwKKBm6EI&s" style="width:30px; height:30px;"> 
                  {% endif %}

              {{ user.username }} <span class="ml-3 text-success" style="font-weight: bold;"> Online <span> 
                <span class="ml-1" style="height: 15px; width: 15px; background-color: #0B920D; border-radius: 50%; display: inline-flex;"></span> <br></p>
            {% else %}
              <p>
                  {% if user.profile.image %}                 
                  <img class="rounded-circle avatar z-depth-1-half mr-1" src="{{user.profile.image.url}}" style="width:30px; height:30px;"> 
                  {% else %}
                   <img class="rounded-circle avatar z-depth-1-half mr-1" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmgQLi9YIA2uiwnuZ_LU_K-nOVMvilA2A5M2dNNescwKKBm6EI&s" style="width:30px; height:30px;"> 
                  {% endif %}
              {{ user.username }} <span class="ml-3 text-dark" style="font-weight: bold;"> Offline <span> 
              <span class="ml-1" style="height: 15px; width: 15px; background-color: #a9a9a9; border-radius: 50%; display: inline-flex;"></span>
              <br></p>
            {% endif %}
          {% endfor %}
          
          </div>
    </div>
  
</div>

{% endblock %}

templates/editProfile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% block content %}

<div class="container">
  <h4 class="text-center font-weight-bold"> My Profile </h4>
  <hr>

  <!--Card-->
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <div class="card card-personal mb-4">

        <!--Card image-->
        <div class="view mx-auto mt-1">
          {% if user.image %}
          <img class="card-img-top" style="border-radius: 50%; height: 150px; width: 150px;" src="{{user.image.url}}"
            alt="Card image cap">
          {% else %}
          <img class="card-img-top" style="border-radius: 50%; height: 150px; width: 150px;"
            src="https://mdbootstrap.com/img/Photos/Avatars/avatar.jpg" alt="Card image cap">
          {% endif %}
          <a href="#!">
            <div class="mask rgba-white-slight"></div>
          </a>
        </div>

        <!--Card image-->

        <!--Card content-->
        <div class="card-body text-center">
          <!--Title-->
          <a>
            <h4 class="card-title">James K</h4>
            <p class="card-text pb-1">{{user.email}}</p>

          </a>
          <form action="{% url 'updateProfilePic' %}" method="post" enctype='multipart/form-data'>
            {% csrf_token %}
            <div class="editProfile">
              {% bootstrap_form editProfileForm layout='inline '%}
            </div>
            <button type="submit" class="btn btn-sm btn-outline-dark-green"><i class="far fa-edit mr-1"
                aria-hidden="true"></i>Edit
              Profile</button type="submit">
          </form>

          <!--Text-->
          <hr>
          <p class="card-meta">Pawame</p>
        </div>
        <!--Card content-->

      </div>
    </div>
  </div>

  <!--Card-->

  {% endblock %}

templates/finance.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}

{% block content %}


<div class="container">
  <h3 class="text-center font-weight-bolder pt-3 pb-3 " style="color: #0B920D;">
Finance Department </h3>
  <hr>

{% if updates %}

{% for update in updates %}

  <div id="{{update.id}}" class="row mt-5">

    <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
      {% if update.user.image %}
        <img class="d-flex rounded-circle avatar z-depth-1-quater mr-3"
          src="{{update.user.image.url}}" height="100px" width="100px" alt="Avatar">
      {% else %}
          <img class="d-flex rounded-circle avatar z-depth-1-half mr-3"
          src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmgQLi9YIA2uiwnuZ_LU_K-nOVMvilA2A5M2dNNescwKKBm6EI&s" height="100px" width="100px" alt="Avatar">
      {% endif %}
    </div>


    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
      <h5 class="mt-0 font-weight-bold dark-text post-content">{{ update.title }}</h5>

      <p class="post-content" style="max-width: 100%;">  
      {% autoescape on %}
        {{ update.update|safe }}
      {% endautoescape %}
      </p>

      <h6 class="text-muted pt-2 post-date">
        <i>Posted by {{ update.user }}: {{ update.time_stamp|timesince }} ago </i>
      </h6>

          <div class="accordion" id="accordionExample275">
                  <button class="btn btn-sm btn-link" type="button" data-toggle="collapse" href="#collapse{{ update.id}}"
                    aria-expanded="false" aria-controls="collapseOne2">
                    View {{ update.comments_set.all|length }} comment{{update.comments_set.all|pluralize}}
                  </button>
              <div id="collapse{{ update.id }}" class="collapse">
                  
                  {% for comment in update.comments_set.all %}

                  <p> 

                  {% if comment.user.image %}

                  
                  <img class="rounded-circle avatar z-depth-1-half mr-1" src="{{comment.user.image.url}}" style="width:30px; height:30px;"> 

                  {% else %}

                   <img class="rounded-circle avatar z-depth-1-half mr-1" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmgQLi9YIA2uiwnuZ_LU_K-nOVMvilA2A5M2dNNescwKKBm6EI&s" style="width:30px; height:30px;"> 

                  {% endif %}
                  
                  <strong> {{ comment.user }}</strong> said: {{ comment.comment }} <br>
                  <span class="text-muted"> {{comment.date_posted|timesince}} ago </span>
                  </p>

                  {% endfor %}

              </div>
            
          </div>
      
      <div class="row mt-3 shadow-textarea">

        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 d-flex">
            {% if request.user.image %}

            <img class="d-flex rounded-circle avatar z-depth-1-half"
              src="{{request.user.image.url}}" height="40px" width="40px"
              alt="Generic placeholder image">
            
            {% else %}
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmgQLi9YIA2uiwnuZ_LU_K-nOVMvilA2A5M2dNNescwKKBm6EI&s" height="40px" width="40px" alt="avatar mx-auto white" class="rounded-circle img-fluid avatar z-depth-1-half">
            {% endif %}


            <a href="{% url 'commenting' update.id%}" style="color: #0B920D"><i class="far fa-comment fa-lg ml-3" aria-hidden="true"></i> Add Comment </a> 

        </div>

  
      </div>
    </div>
  </div>

{% endfor %}

{% else %}
    <p class="text-center" style="color: #0B920D;">No updates posted yet </p>
{% endif %}

    <div class="row onlineUsers">
          <button id="popover" class="btn btn-sm btn-green ml-auto" title="Employee Online Status" data-toggle="popover"  data-placement="top" data-trigger="focus"> Who's online? </button>

          <div id="popover-content" style="display:none;">
          {% for user in users %}
            {% if user.is_online %}
              <p>
                  {% if user.image %}                 
                  <img class="rounded-circle avatar z-depth-1-half mr-1" src="{{user.image.url}}" style="width:30px; height:30px;"> 
                  {% else %}
                   <img class="rounded-circle avatar z-depth-1-half mr-1" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmgQLi9YIA2uiwnuZ_LU_K-nOVMvilA2A5M2dNNescwKKBm6EI&s" style="width:30px; height:30px;"> 
                  {% endif %}

              {{ user.username }} <span class="ml-3 text-success" style="font-weight: bold;"> Online <span> 
                <span class="ml-1" style="height: 15px; width: 15px; background-color: #0B920D; border-radius: 50%; display: inline-flex;"></span> <br></p>
            {% else %}
              <p>
                  {% if user.image %}                 
                  <img class="rounded-circle avatar z-depth-1-half mr-1" src="{{user.image.url}}" style="width:30px; height:30px;"> 
                  {% else %}
                   <img class="rounded-circle avatar z-depth-1-half mr-1" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmgQLi9YIA2uiwnuZ_LU_K-nOVMvilA2A5M2dNNescwKKBm6EI&s" style="width:30px; height:30px;"> 
                  {% endif %}
              {{ user.username }} <span class="ml-3 text-dark" style="font-weight: bold;"> Offline <span> 
              <span class="ml-1" style="height: 15px; width: 15px; background-color: #a9a9a9; border-radius: 50%; display: inline-flex;"></span>
              <br></p>
            {% endif %}
          {% endfor %}
          
          </div>
    </div>
  
</div>

{% endblock %}

templates/human_resource.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}

{% block content %}


<div class="container">
  <h3 class="text-center font-weight-bolder pt-3 pb-3 " style="color: #0B920D;">
Human Resource Department </h3>
  <hr>

{% if updates %}

{% for update in updates %}

  <div id="{{update.id}}" class="row mt-5">

    <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
      {% if update.user.image %}
        <img class="d-flex rounded-circle avatar z-depth-1-quater mr-3"
          src="{{update.user.image.url}}" height="100px" width="100px" alt="Avatar">
      {% else %}
          <img class="d-flex rounded-circle avatar z-depth-1-half mr-3"
          src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmgQLi9YIA2uiwnuZ_LU_K-nOVMvilA2A5M2dNNescwKKBm6EI&s" height="100px" width="100px" alt="Avatar">
      {% endif %}
    </div>


    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
      <h5 class="mt-0 font-weight-bold dark-text post-content">{{ update.title }}</h5>

      <p class="post-content" style="max-width: 100%;">  
      {% autoescape on %}
        {{ update.update|safe }}
      {% endautoescape %}
      </p>

      <h6 class="text-muted pt-2 post-date">
        <i>Posted by {{ update.user }}: {{ update.time_stamp|timesince }} ago </i>
      </h6>

          <div class="accordion" id="accordionExample275">
                  <button class="btn btn-sm btn-link" type="button" data-toggle="collapse" href="#collapse{{ update.id}}"
                    aria-expanded="false" aria-controls="collapseOne2">
                    View {{ update.comments_set.all|length }} comment{{update.comments_set.all|pluralize}}
                  </button>
              <div id="collapse{{ update.id }}" class="collapse">
                  
                  {% for comment in update.comments_set.all %}

                  <p> 

                  {% if comment.user.image %}

                  
                  <img class="rounded-circle avatar z-depth-1-half mr-1" src="{{comment.user.image.url}}" style="width:30px; height:30px;"> 

                  {% else %}

                   <img class="rounded-circle avatar z-depth-1-half mr-1" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmgQLi9YIA2uiwnuZ_LU_K-nOVMvilA2A5M2dNNescwKKBm6EI&s" style="width:30px; height:30px;"> 

                  {% endif %}
                  
                  <strong> {{ comment.user }}</strong> said: {{ comment.comment }} <br>
                  <span class="text-muted"> {{comment.date_posted|timesince}} ago </span>
                  </p>

                  {% endfor %}

              </div>
            
          </div>
      
      <div class="row mt-3 shadow-textarea">

        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 d-flex">
            {% if request.user.image %}

            <img class="d-flex rounded-circle avatar z-depth-1-half"
              src="{{request.user.image.url}}" height="40px" width="40px"
              alt="Generic placeholder image">
            
            {% else %}
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmgQLi9YIA2uiwnuZ_LU_K-nOVMvilA2A5M2dNNescwKKBm6EI&s" height="40px" width="40px" alt="avatar mx-auto white" class="rounded-circle img-fluid avatar z-depth-1-half">
            {% endif %}


            <a href="{% url 'commenting' update.id%}" style="color: #0B920D"><i class="far fa-comment fa-lg ml-3" aria-hidden="true"></i> Add Comment </a> 

        </div>

  
      </div>
    </div>
  </div>

{% endfor %}

{% else %}
    <p class="text-center" style="color: #0B920D;">No updates posted yet </p>
{% endif %}

    <div class="row onlineUsers">
          <button id="popover" class="btn btn-sm btn-green ml-auto" title="Employee Online Status" data-toggle="popover"  data-placement="top" data-trigger="focus"> Who's online? </button>

          <div id="popover-content" style="display:none;">
          {% for user in users %}
            {% if user.is_online %}
              <p>
                  {% if user.image %}                 
                  <img class="rounded-circle avatar z-depth-1-half mr-1" src="{{user.image.url}}" style="width:30px; height:30px;"> 
                  {% else %}
                   <img class="rounded-circle avatar z-depth-1-half mr-1" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmgQLi9YIA2uiwnuZ_LU_K-nOVMvilA2A5M2dNNescwKKBm6EI&s" style="width:30px; height:30px;"> 
                  {% endif %}

              {{ user.username }} <span class="ml-3 text-success" style="font-weight: bold;"> Online <span> 
                <span class="ml-1" style="height: 15px; width: 15px; background-color: #0B920D; border-radius: 50%; display: inline-flex;"></span> <br></p>
            {% else %}
              <p>
                  {% if user.image %}                 
                  <img class="rounded-circle avatar z-depth-1-half mr-1" src="{{user.image.url}}" style="width:30px; height:30px;"> 
                  {% else %}
                   <img class="rounded-circle avatar z-depth-1-half mr-1" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmgQLi9YIA2uiwnuZ_LU_K-nOVMvilA2A5M2dNNescwKKBm6EI&s" style="width:30px; height:30px;"> 
                  {% endif %}
              {{ user.username }} <span class="ml-3 text-dark" style="font-weight: bold;"> Offline <span> 
              <span class="ml-1" style="height: 15px; width: 15px; background-color: #a9a9a9; border-radius: 50%; display: inline-flex;"></span>
              <br></p>
            {% endif %}
          {% endfor %}
          
          </div>
    </div>
  
</div>

{% endblock %}